### ISSUE TITLE
Make clearer who the maintainer is in README

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/privatemsg#13]
@Graham-72 are you also the maintainer?

**Comment by Radcliffe** [comment]
I think that we should release a new version as soon as practical, because there are major bugs in the current release. I am willing to volunteer if the module is currently unmaintained.

Edit: I just noticed that it hasn't been released yet. What would it take to get it ready for release?

**Comment by Graham-72** [comment]
@herbdool no I would prefer not to be the maintainer. I would be very happy if @Radcliffe is prepared to take this on.

Perhaps we need a label 'unmaintained' for abandoned projects?

**Comment by Radcliffe** [comment]
Thanks Graham. I am prepared to take on the role of maintainer, and I have edited the README accordingly.
