### ISSUE TITLE
Unable to send private messages

### ISSUE THREAD

**Issue by Radcliffe** [backdrop-contrib/privatemsg#16]
When I go to /messages/new and I try to send a private message, I get a white screen instead, and the system logs contain the following error message.

> PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop.role' doesn't exist: SELECT role.* FROM {role} role WHERE (role.name LIKE :db_condition_placeholder_0 ESCAPE '\\') AND (role.rid <> :db_condition_placeholder_1) ORDER BY role.name ASC LIMIT 10 OFFSET 0; Array ( [:db_condition_placeholder_0] => david% [:db_condition_placeholder_1] => BACKDROP_ANONYMOUS_RID ) in privatemsg_roles_autocomplete() (line 115 of [...]/modules/contrib/privatemsg/privatemsg_roles/privatemsg_roles.module).

There are four lines in the module code that attempt to query the {role} table. No table exists with this name in Backdrop, although it exists in Drupal 7. Each of these queries must be rewritten to work in Backdrop.

**Comment by deaddred** [comment]
I had a backup copy of PM  from April 24th that I just installed and that one does send out email notifications. The newest version one is totally wonky :)

**Comment by Radcliffe** [comment]
Note that the privatemsg_roles module is not working and it should be disabled for now. See #3.
