### ISSUE TITLE
Message body token [privatemsg_message:url] causing errors

### ISSUE THREAD

**Issue by deaddred** [backdrop-contrib/privatemsg#27]
Using May 4th build If I use [privatemsg_message:url] in the E-mail Notify body settings I get a white screen with the following error after clicking the send button on a new message.

Error: Call to undefined method stdClass::uri() in entity_uri() (line 572 of /home/####/public_html/core/modules/entity/entity.module).

**Comment by Radcliffe** [comment]
Does the above patch fix the problem?

**Comment by deaddred** [comment]
Hi
Yes just tested it and it's working :)
