### ISSUE TITLE
account [user] gets inserted into TO field

### ISSUE THREAD

**Issue by deaddred** [backdrop-contrib/privatemsg#29]
Weird thing started to happen. When using a link from the profile page or from a views constructed link domain.com/messages/new/178?destination=user/178 or domain.com/messages/new/178  The TO field gets populated with the recipients user name followed by [user]

I've attached an image

**Comment by deaddred** [comment]
Ah the submit form is bugged can't add images. Here's a link to it  https://www.gtrader.ca/bugs/msg-user.png

**Comment by Radcliffe** [comment]
This is surprising, but it seems to me that the message is being sent correctly. I think that [user] is being inserted because it is also possible to send messages by role, and the name of a role could be the same as the name of a user. So I think that it is working as designed.

**Comment by herbdool** [comment]
This is as expected.
