### ISSUE TITLE
Clicking message on messages page gives Error Object of class stdClass could not be converted to string

### ISSUE THREAD

**Issue by JugglingCoder** [backdrop-contrib/privatemsg#31]
privatemsg was working pretty good for me with earlier versions of Backdrop but with newer releases it is giving me an issue (can't recall exactly from which version of Backdrop this started happening).

On the /messages page when clicking a message (with an URL like: /messages/view/1), I get the error:

Error
Object of class stdClass could not be converted to string
Error message
Recoverable fatal error: Object of class stdClass could not be converted to string in DatabaseStatementBase->execute() (line 2242 of \core\includes\database\database.inc).

I'll try to look into this and see if I can figure it out with my limited PHP knowledge but any help would be appreciated.

**Comment by JugglingCoder** [comment]
I fixed (or maybe the correct word is "hacked") this to work by:

In the file: privatemsg.module
the function: privatemsg_message_load_multiple
calls: entity_load
like this: $result = entity_load_multiple('privatemsg_message', $pmids, $conditions, $reset);

the var $conditions is supposed to be an ARRAY but this var ($conditions) is the user account in an OBJECT.

So I just created an ARRAY with the user's id and passed that:
$conditions = $conditions['account'];
$uid = $conditions->uid;
$conditions = array('author' => $uid);

And it worked.  The user that created the message can now read his own message.....
HOWEVER,
when the person the user sent that message to tries to read it,
"You are not authorized to access this page. "
I've checked all permissions a couple times and permissions are set correctly....
pressing on.

**Comment by docwilmot** [comment]
Is this module abandoned? No release yet? For anyone trying to solve this issue, it may be the result of the changes to the DefaultEntityController code to add entity caching. So to get this to work, would need to override the `DefaultEntityController::load()` function and add the code below to it:
```
...
    // Use an entity field query to transform the list of conditions into
    // the set of entity IDs which the conditions admit, then re-enter this
    // method with that set as the $ids constraint.
    if ($conditions && !$revision_id) {

    //ADD THE CODE BELOW, IN THIS POSITION.
    if (isset($conditions['account'])) {
      $this->account = $conditions['account'];
      unset($conditions['account']);
    }
```

**Comment by JugglingCoder** [comment]
Wow, Thank you very much docwilmot! This works! This is a 'hack' to a core file 'entity.controller.inc' so... I guess I'll just have to remember to hack this file every time Backdrop updates but at least it's working now.  I would have never figured that one out on my own, greatly appreciate it.

**Comment by docwilmot** [comment]
Oh I should clarify, wasnt recommending hacking `entity.controller.inc`. I meant you should override `DefaultEntityController::load()`, meaning copy the load function to `privatemsg.controller.inc` and add that bit of code there. Also, this was indeed a quick hack, not sure if other things may be not working properly long term.

**Comment by JugglingCoder** [comment]
Ah, yes, I understand.  Thank you for the update.  Yep, I understand it's a quick hack but at least it's working for now.
