### ISSUE TITLE
1048 Column 'email_notify_is_enabled' cannot be null Pull request for Issue #30

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/privatemsg#39]
Just installed and configured the Messaging settings...  
Setup permissions
Then added a user "steveedit"
Added Mail and Mime Mail modules... but not enabled...  

Tried to set new password from email link with "steveedit" and received this error...

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email_notify_is_enabled' cannot be null 

![image](https://github.com/backdrop-contrib/privatemsg/assets/1705388/afe47e3b-2723-4c6d-af60-841db0081c4d)

Changed the URL from /user/reset/,token. to the site URL and was logged in.

**Comment by albanycomputers** [comment]
Looking into this... edited user "steveedit" and removed "Receive email notification for incoming private messages" option... 

Saved and the option is still checked...

![image](https://github.com/backdrop-contrib/privatemsg/assets/1705388/97710ad6-9783-4092-a4c3-a0d27ce18b61)

**Comment by albanycomputers** [comment]
getting SQL error when trying to change the setting when logged in as the user.

**Comment by albanycomputers** [comment]
Seems to be when the user does not have permission to change whether they can enable/disable private messages.

Looks like the code in pm_email_notify.module - line 122 - function "function pm_email_notify_user_update($account)"

```code
function pm_email_notify_user_update($account) {
  if (privatemsg_user_access('read privatemsg', $account)) {
    db_merge('pm_email_notify')
      ->fields(array('email_notify_is_enabled' => $account->pm_enable)
      ->key(array('user_id' => $account->uid))
      ->execute();
  }
}
```
setting "pm_enable" seems to be used to show if the user can change whether they can disable their participation in the sending and receiving of private messages... but when they don't have permission to change it, the settings aren't displayed... and the pm_enabled is always NULL... causing the error.

I think it should be
```code
function pm_email_notify_user_update($account) {
  if (privatemsg_user_access('read privatemsg', $account)) {
    db_merge('pm_email_notify')
      ->fields(array('email_notify_is_enabled' => $account->pm_send_notifications))
      ->key(array('user_id' => $account->uid))
      ->execute();
  }
}
```
the "pm_send_notifications" is for when the user wants to enable/disable the receiving notifications of new messages.

**Comment by albanycomputers** [comment]
Still happening when a new user enters their password for the first time

**Comment by herbdool** [comment]
I looked through the file's history and indeed it got changed from `$edit['pm_send_notifications']` when ported so setting it back to `$account->pm_send_notifications` fixes it.
