### ISSUE TITLE
Link to send user a message on their own user account page

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/privatemsg#40]
When visiting the user account page /accounts/<user> it has a link to send them a message...

![image](https://github.com/backdrop-contrib/privatemsg/assets/1705388/28f7fad4-0b95-4e82-9c4c-905fb895b337)

Just added the code to change it so :-
![image](https://github.com/backdrop-contrib/privatemsg/assets/1705388/c9c3b15e-9670-4955-8c63-3e4f74144a14)

But not sure how to share it... it said I couldn't add it to your PR... so It suggested I create my own... which I did.

**Comment by herbdool** [comment]
I don't see a PR for it. Sometimes I accidentally create the PR against my own fork. Maybe that's what happened to you too?

**Comment by albanycomputers** [comment]
I got lost with what I needed to do so left it and got it working on my local computer...

**Comment by albanycomputers** [comment]
Could be because I tried to do a PR on your PR...

**Comment by albanycomputers** [comment]
Just figured out how to do it...  not sure I've done it correctly :)

PR#43

**Comment by herbdool** [comment]
I see the PR, great! @albanycomputers One more small thing you can do: on the PR body text, type in `Fixes #40` and it will automatically link the issue and the PR together. The link to the PR will appear on the top of the issue. I'll do it this time so you'll see.
