### ISSUE TITLE
Config files not removed after uninstalling

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/privatemsg#41]
After uninstalling the module, the following config files are not removed.

- pm_block_user.settings.json
- pm_email_notify.settings.json
- privatemsg_filter.settings.json
- privatemsg_limits.settings.json

**Comment by herbdool** [comment]
@albanycomputers is this issue in regards to the PR I just made for #30? If so can you put all the feedback in that thread? Otherwise it's unclear what needs to get fixed.

**Comment by herbdool** [comment]
I've just tried uninstalling the module while on the #30 branch and all the config files were removed. I can't replicate.

**Comment by albanycomputers** [comment]
I'll have another play on a fresh install.

**Comment by herbdool** [comment]
I'm closing until this can be replicated.
