### ISSUE TITLE
Messages are not being listed in Inbox column.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/privatemsg#5]
Incoming messages are appearing in the 'All messages' column but not in the 'Inbox' column.

**Comment by bd0bd** [comment]
I have no any Incoming messages folder/tab.
I have plain list.

**Comment by Graham-72** [comment]
@bd0bd at /messages I see a display like this
![messages 1 new - backdrop starter 2016-08-09 19-42-44](https://cloud.githubusercontent.com/assets/10559274/17529081/df2d66a0-5e69-11e6-8040-da3d7de83b9b.png)

Do you see this?
If so can you select the different coloumns? For example 'All messages'?

**Comment by bd0bd** [comment]
I do not have these tabs.

![bbb](https://cloud.githubusercontent.com/assets/13515302/17531054/f901ea7e-5e82-11e6-857e-7ff540cf07df.png)

**Comment by Graham-72** [comment]
Strange!
Do you have Ajax functioning for your test site?

**Comment by bd0bd** [comment]
I have found the reason.
To see these tabs I need to activate **Privatemsg roles** sub-module.

**Comment by bd0bd** [comment]
I have the same — new message in All messages.
Moreover, if I click **Messages (1 new)** link then nothing happens.

**Comment by Graham-72** [comment]
OK.
And I need to revise the privatemsg roles sub-module for Backdrop - issue #3.

**Comment by Graham-72** [comment]
> if I click Messages (1 new) then nothing happens.

Do you mean the Messages (1 new) link in your user menu? If I click this is brings up the display in the screenshot I posted above, but not the one you posted.

**Comment by bd0bd** [comment]
> Do you mean the Messages (1 new) link in your user menu? 

My account, Log out on right coner

**Comment by bd0bd** [comment]
@@I will deactivate all sub-modules.
The main module works fine.

**Comment by Radcliffe** [comment]
The problem does not occur for me when all submodules are deactivated, but it occurs when the filter submodule is enabled.

**Comment by herbdool** [comment]
Works for me with all sub-modules enabled. Closing
