### ISSUE TITLE
Private message settings on user account page even if they don't have permission for private messages 

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/privatemsg#51]
On a brand new install..., added module then added a user... did not add any permissions and the Private Message user settings are available on their page. 

It's a bit of a strange one...  logged in as admin... I would expect the options to be greyed out if the user can't read private messages... although it's a catch 22...  

![image](https://github.com/backdrop-contrib/privatemsg/assets/1705388/a5f2dd69-ac56-4502-95e5-505177cc6cf5)

I un-checked the "Receive email notification for incoming private messages" option and saved settings but it wouldn't save the state...

I updated the permissions and it did.

This is a bug when logged in as admin.

When the user logs in and visits their page the options are not being displayed.

**Comment by herbdool** [comment]
I've addressed this in another issue (kind of). The option is disabled if the user is not allowed to disable private message.
