### ISSUE TITLE
SQL Error on Password Rest URL after setting new password.

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/privatemsg#53]
Logged out and requested a Reset Password... 

After setting the password I got this error.

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email_notify_is_enabled' cannot be null 

You can go to the normal URL for the site and the error is not shown again.

**Comment by albanycomputers** [comment]
Only seems to happen on reset...  

I added the 

```code
  if (is_null($account->pm_send_notifications)) {
      $account->pm_send_notifications = FALSE;
    }
```
to the function at line 120 in pm_email_notify.module and got a different error about date format

"EntityStorageException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `backdrop-3230372574`.`pm_email_notify`.`email_notify_is_enabled` at row 1 in EntityDatabaseStorageController->save() (line 789 of /home/sites/1a/2/xyz/public_html/core/modules/entity/entity.controller.inc)."

```code
function pm_email_notify_user_update($account) {
  debug($account);
  if (privatemsg_user_access('read privatemsg', $account)) {
    if (is_null($account->pm_send_notifications)) {
      $account->pm_send_notifications = FALSE;
    }

    db_merge('pm_email_notify')
      ->fields(array('email_notify_is_enabled' => $account->pm_send_notifications))
      ->key(array('user_id' => $account->uid))
      ->execute();
  }
}
```

Only seems to happen on password reset but still allows you to login.

**Comment by albanycomputers** [comment]
Changed the "false" to 0 and it works.... YEAH!!!!!!

**Comment by albanycomputers** [comment]
However... this then uncheckes the permission... 
![image](https://github.com/backdrop-contrib/privatemsg/assets/1705388/5f722c81-4190-4bd4-b3b8-8f93009a4533)

So, the "$account->pm_send_notifications" value isn't available in the $account object if there is a password reset.

**Comment by albanycomputers** [comment]
Sorted...   See PR

**Comment by herbdool** [comment]
Thanks @albanycomputers. I'll have a look soon. I see you added a "Fixed ...". It goes in the text body, not the title, if you want to link the PR to the issue.
