### ISSUE TITLE
Errors at /admin/config/search/path/patterns

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/privatemsg#8]
![ddd](https://cloud.githubusercontent.com/assets/13515302/17558795/7e407664-5f24-11e6-839f-aa916d968d4c.png)

**Comment by Graham-72** [comment]
@bd0bd it seems that something in privatemsg.module is interfering with tokens. I have narrowed one issue down to the class PrivatemsgMessageController in that module which extends DefaultEntityController. I am a complete novice with programming relating to entities so it may take me a while to identify the cause of the problem, and issue #6 .

**Comment by Radcliffe** [comment]
Fixed by PR#12. See issue #9.
