### ISSUE TITLE
!Important! By enabling  Private Messages you will mess up Site Tokens

### ISSUE THREAD

**Issue by JugglingCoder** [backdrop-contrib/privatemsg#9]
After enabling Private Messages when a new user registers and the New User email is sent... the "tokens" such as "username", "website", etc. are missing from the email.  I tried to debug the module a bit... but... couldn't narrow it down (was commenting out functions etc. but still was messing up the sent out email).

**Comment by JugglingCoder** [comment]
I have confirmed this again with 2 sites now.  When enabling Private Messages it messes up most the site tokens... I have no idea why.  Once enabled, Webform was not able to send the webforms field data by email to designated email address AND when creating a user account all the tokens at "Account Emails" will be empty.

**Comment by JugglingCoder** [comment]
Problem:
When enabling Private Messages, the "Tokens" used in Webform and Account Emails become "blank" (empty).

My OOP level is not very high and I don't really understand the flow of the Private Messages Module but after extensive trial and error I found the problem function,
File:
/privatemsg/privatemsg.module
Function:
```php
/**
 * Private message controller, loads private messages.
 */
class PrivatemsgMessageController extends DefaultEntityController
```

Notes:
1.) by commenting out the entire function, the tokens for Webform and Account Emails WORK.
2.) by commenting out the internal functions of this funtion (and leave only the function itself) will still make the Webform and Account Email tokens FAIL. So, just by having this function in the module, the tokens fail.
3.) I tried commenting out this:
hook_autoload_info [ https://api.backdropcms.org/api/backdrop/core!modules!system!system.api.php/function/hook_autoload_info/1 ]
If I comment out the:
function privatemsg_autoload_info() {
function, the tokens still are broken
4.) in the Drupal version of Private messages the function is named:
class PrivatemsgMessageController extends DrupalDefaultEntityController {
other than that the internal code of the function is exactly the same.

**Comment by JugglingCoder** [comment]
I have solved this issue... but have no idea how to change this actual module (or if you want me to).

I kept at it a bit and got LUCKY! Searched for "Backdrop DefaultEntityController" in google and found this thread:
https://github.com/backdrop/backdrop-issues/issues/710
quicksketch said, "So to fix this, you need to move that class into a separate file. Then use hook_autoload_info() to point at it."
I honestly have no idea what he is talking about with the controller stuff but did as he said.  I moved the:
class PrivatemsgMessageController extends DefaultEntityController {
to it's own file called:
privatemsg.controller.inc
Then in:
function privatemsg_autoload_info() {
I changed from this:
'PrivatemsgMessageController' => 'privatemsg.module',
to this:
'PrivatemsgMessageController' => 'privatemsg.controller.inc',
and... it WORKS.  The "tokens" are being sent in the emails for Webform and Account Emails correctly.

**Comment by Graham-72** [comment]
@JugglingCoder thank you for reporting this issue and well done for finding a solution. As I did the original porting work I will be happy to help get your amendment included, but at the moment I am on holiday and have limited wifi access. So, maybe in two weeks time I can get to it.

**Comment by JugglingCoder** [comment]
No problem Graham-72, thank you for the port.

**Comment by deaddred** [comment]
I can confirm that putting the  class PrivatemsgMessageController extends DefaultEntityController into its own file works.
